import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Discord Clone",
  description:
    "Real-time chat, voice, and community features in a modern, scalable Next.js 14-powered platform.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "liveblocks",
    "livekit",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "discord-clone",
    "realtime-chat",
    "live-audio",
    "live-video",
    "live-chat",
    "neon-db",
    "sonner",
    "zustand",
    "zod",
    "sql",
    "postgresql",
    "aiven",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "scss",
    "sass",
    "web",
    "web-dev",
    "web-development",
    "web-design",
    "web-designer",
    "web-designing",
    "web-developer",
    "web-developing",
    "neon",
    "neon-db",
    "neon-database",
    "neon-database-url",
    "uploadthing",
    "uploadthing-secret",
    "uploadthing-app-id",
    "clerk",
    "clerk-publishable-key",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma",
    url: "https://github.com/idityage",
  },
} as const;

export const links = {
  sourceCode: "https://github.com/idityage/discord-app",
} as const;
